---
label: default
hide_body: false
is_partial: false
fields:
- name: layout
  label: Layout
  type: text
  hidden: false
  default: default
- type: text
  label: correo Electrónico
  name: un_text
pages:
- hello.md
